In [1]:
import numpy as np

In [2]:
arr1d=np.array([1,2,3,4,5,6])
print(arr1d)

[1 2 3 4 5 6]


In [3]:
arr1d.ndim



1

In [6]:
a2d=np.array([[12,3,4,3,5,3,3],[12,3,4,3,5,3,3],[12,3,4,5,3,3,3],[12,3,4,5,3,3,3],[12,3,4,5,3,3,3]])
print(a2d)

[[12  3  4  3  5  3  3]
 [12  3  4  3  5  3  3]
 [12  3  4  5  3  3  3]
 [12  3  4  5  3  3  3]
 [12  3  4  5  3  3  3]]


In [8]:
a2d.ndim


2

In [9]:
a2d.size

35

In [10]:
a2d.shape

(5, 7)