In [1]:
import numpy as np

In [2]:
mx=np.array([2,4,5])
print(mx)

[2 4 5]


In [3]:
mx=np.ones((3,4))
print(mx)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
print(mx.dtype)

float64


In [6]:
mx=np.ones((10,10),int)
print(mx)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [7]:
mx=np.empty((49,49))
print(mx)

[[1.16382452e-311 1.16385736e-311 7.74860419e-304 ... 7.74860419e-304
  7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304 ... 7.74860419e-304
  7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304 ... 7.74860419e-304
  7.74860419e-304 7.74860419e-304]
 ...
 [7.74860419e-304 7.74860419e-304 7.74860419e-304 ... 7.74860419e-304
  7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304 ... 7.74860419e-304
  7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304 ... 7.74860419e-304
  7.74860419e-304 7.74860419e-304]]


In [13]:

mx=np.arange(2,48,2)
print(mx)


[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46]


In [16]:
mx=np.ones((4))
print(mx)

[1. 1. 1. 1.]
